model: SASRec
data_type: sequential
reprocess: true
fair-rank: false
rank_model: FOCF
use_llm: false
log_name: SASRec_LastFM
device: cpu
epoch: 20
batch_size: 64
learning_rate: 0.001
mmf_eval_ratio: 0.5
decimals: 4
eval_step: 5
eval_type: ranking
watch_metric: mmf@20
topk:
- 5
- 10
- 20
store_scores: true
fairness_metrics:
- MinMaxRatio
- MMF
- GINI
- Entropy
fairness_type: Exposure
